(function(){'use strict';
var sections=[
['1. Pain & Symptom Profile',['Pain location / distribution','Onset & duration','Aggravating factors','Easing factors','24-hour pattern / irritability']],
['2. Safety & Screening',['Red-flag screening','Neurological screen','Precautions / contraindications']],
['3. Functional Assessment',['Activity limitations','Participation restrictions','Patient goals','Outcome measure & baseline']],
['4. Objective Examination',['Regional ROM / movement quality','MMT / strength pattern','Special tests','Palpation / symptom reproduction','Gait / functional movement']],
['5. Clinical Impression',['Key impairments','Clinical priorities','Working clinical impression','Assessment plan / reassessment criteria']]
];
function css(){if(document.getElementById('movia-v3-css'))return;var s=document.createElement('style');s.id='movia-v3-css';s.textContent='.movia-v3{margin-top:20px;border:1px solid #dce7ea;border-radius:16px;background:#fff;padding:22px}.movia-v3-head{display:flex;justify-content:space-between;gap:15px;align-items:center;margin-bottom:18px}.movia-v3-title{font-size:18px;font-weight:700}.movia-v3-sub{display:block;color:#718087;font-size:12px;margin-top:4px}.movia-v3-badge{font-size:11px;font-weight:700;padding:7px 10px;border-radius:999px;background:#e8f7f8;color:#167b83}.movia-v3-sec{border-top:1px solid #e5edef;padding:18px 0}.movia-v3-sec:first-of-type{border-top:0}.movia-v3-sec h4{margin:0 0 12px;font-size:14px}.movia-v3-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.movia-v3-field label{display:block;font-size:12px;font-weight:600;margin-bottom:6px}.movia-v3-field textarea{width:100%;box-sizing:border-box;min-height:58px;border:1px solid #d8e3e6;border-radius:9px;padding:10px;font:inherit;resize:vertical}.movia-v3-foot{display:flex;justify-content:space-between;align-items:center;gap:15px;border-top:1px solid #e5edef;padding-top:16px}.movia-v3-note{font-size:11px;color:#718087}@media(max-width:700px){.movia-v3-grid{grid-template-columns:1fr}.movia-v3-head,.movia-v3-foot{align-items:flex-start;flex-direction:column}}';document.head.appendChild(s)}
function mount(){css();var pages=document.querySelectorAll('#app .page');for(var i=0;i<pages.length;i++){var p=pages[i];if(!p.querySelector('.tabs'))continue;if(p.querySelector('.movia-v3'))continue;var marker=p.querySelector('textarea');if(!marker)continue;var box=document.createElement('section');box.className='movia-v3';var html='<div class="movia-v3-head"><div><div class="movia-v3-title">COMPREHENSIVE CLINICAL ASSESSMENT</div><span class="movia-v3-sub">Structured physiotherapy documentation for clinician review</span></div><span class="movia-v3-badge">MOVIA V1</span></div>';for(var j=0;j<sections.length;j++){var sec=sections[j];html+='<div class="movia-v3-sec"><h4>'+sec[0]+'</h4><div class="movia-v3-grid">';for(var k=0;k<sec[1].length;k++){html+='<div class="movia-v3-field"><label>'+sec[1][k]+'</label><textarea rows="2" placeholder="Document clinical findings..."></textarea></div>'}html+='</div></div>'}html+='<div class="movia-v3-foot"><div class="movia-v3-note">Structured decision support only. Final clinical judgement remains with the treating physiotherapist.</div><button type="button" class="primary" id="movia-v3-save">Save Comprehensive Assessment</button></div>';box.innerHTML=html;var actions=p.querySelector('.actions');if(actions)actions.parentNode.insertBefore(box,actions);else p.appendChild(box);box.querySelector('#movia-v3-save').addEventListener('click',function(){var b=this;b.textContent='Assessment Saved ✓';setTimeout(function(){b.textContent='Save Comprehensive Assessment'},1800)})}}
function boot(){mount();new MutationObserver(function(){mount()}).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setInterval(mount,300)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();
